language: csharp
mono: none
dotnet: 6.0
solution: SortingApp.sln
install:
  - install -d -m 0755 $HOME/.nuget
  - nuget restore SortingApp.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release SortingApp.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./UnitTests.Tests/bin/Release/UnitTests.Tests.dll