language: csharp
mono: none
dotnet: 6.0
solution: SortingApp.sln
install:
  - sudo apt-get install nuget
  - nuget restore SortingApp.sln
  - nuget install xunit.runners -Version 2.5.1 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release SortingApp.sln
  - mono ./testrunner/xunit.runners.2.5.1/tools/xunit.console.clr4.exe ./UnitTests.Tests/bin/Release/UnitTests.Tests.dll